### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by doxakis**

### CODE REVIEW

**Comment by Belval** [comment]
I'm pretty sure the correct formulation is 'Hi' what do you think @Captaincyr?

**Comment by lalevac** [comment]
I'm not sure this PR fixes the underlying issue. I suggest adding some kind of mechanism to allow for 
 localization of the alerted message.

**Comment by Gcaya** [comment]
Totally agree with Mister @ModoNoob , what about the people from Nigeria?
And I think you should add some comments, its not totally clear at first sight what this function does.

**Comment by jeremiedcyr** [comment]
To be honest, if you want me to change what is shown in the alert dialog, you should make a function that returns the right word for each language.

**Pull request closed without merging**
